// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esuascsrlfdbcpikzvlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzdWFzY3NybGZkYmNwaWt6dmxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjczMjEsImV4cCI6MjA3NDMwMzMyMX0.ySDA7sSX9g57F4csJ8ypqFGzdj_aVH9hxuHd0qlQylU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});